/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libkedf_LibKEDF */

#ifndef _Included_libkedf_LibKEDF
#define _Included_libkedf_LibKEDF
#ifdef __cplusplus
extern "C" {
#endif
#undef libkedf_LibKEDF_serialVersionUID
#define libkedf_LibKEDF_serialVersionUID 20161024LL
/*
 * Class:     libkedf_LibKEDF
 * Method:    initializeRegularGrid
 * Signature: (III[D[D[D)J
 */
JNIEXPORT jlong JNICALL Java_libkedf_LibKEDF_initializeRegularGrid
  (JNIEnv *, jclass, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     libkedf_LibKEDF
 * Method:    initializeOpenCLGrid
 * Signature: (III[D[D[DII)J
 */
JNIEXPORT jlong JNICALL Java_libkedf_LibKEDF_initializeOpenCLGrid
  (JNIEnv *, jclass, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     libkedf_LibKEDF
 * Method:    initializeTF
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_libkedf_LibKEDF_initializeTF
  (JNIEnv *, jclass, jlong);

/*
 * Class:     libkedf_LibKEDF
 * Method:    initializeVW
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_libkedf_LibKEDF_initializeVW
  (JNIEnv *, jclass, jlong);

/*
 * Class:     libkedf_LibKEDF
 * Method:    initializeATFBVW
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_libkedf_LibKEDF_initializeATFBVW
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     libkedf_LibKEDF
 * Method:    initializeWT
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_libkedf_LibKEDF_initializeWT
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     libkedf_LibKEDF
 * Method:    initializeTayloredWGC
 * Signature: (JIDDDD)V
 */
JNIEXPORT void JNICALL Java_libkedf_LibKEDF_initializeTayloredWGC
  (JNIEnv *, jclass, jlong, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     libkedf_LibKEDF
 * Method:    initializeHC
 * Signature: (JDDDDD)V
 */
JNIEXPORT void JNICALL Java_libkedf_LibKEDF_initializeHC
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     libkedf_LibKEDF
 * Method:    calcEnergy
 * Signature: (J[D)D
 */
JNIEXPORT jdouble JNICALL Java_libkedf_LibKEDF_calcEnergy
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     libkedf_LibKEDF
 * Method:    calcPotential
 * Signature: (J[D[D)D
 */
JNIEXPORT jdouble JNICALL Java_libkedf_LibKEDF_calcPotential
  (JNIEnv *, jclass, jlong, jdoubleArray, jdoubleArray);

/*
 * Class:     libkedf_LibKEDF
 * Method:    cleanup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_libkedf_LibKEDF_cleanup
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
